trigger:
  branches:
    include:
      - main

variables:
  - group: TerraformSecrets

stages:
  - stage: Terraform
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo "Installing Terraform"
                curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.8.0/terraform_1.8.0_linux_amd64.zip
                unzip terraform.zip
                sudo mv terraform /usr/local/bin/
                terraform -version
            displayName: 'Install Terraform'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                terraform init
              workingDirectory: infra/
            displayName: 'Terraform Init'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                terraform plan -out=tfplan
              workingDirectory: infra/
            displayName: 'Terraform Plan'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                terraform apply -auto-approve tfplan
              workingDirectory: infra/
            displayName: 'Terraform Apply'
